'use client';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import type { CSSProperties, PointerEvent } from 'react';
type Particle = {id:number;x:number;y:number;glyph:string};
const links=[['Services','#services'],['Our approach','#approach'],['Learn','#learn']];
const services=[['01','Less repetition. More progress.','Connect your forms, spreadsheets and everyday tools. Let routine updates and follow-ups happen without the chasing.','Workflow automation'],['02','Software shaped around your work.','A dashboard, a customer portal, or an internal assistant. Built for the way your business actually operates.','Custom software & AI assistants'],['03','Clarity before complexity.','Find the right starting point, choose what is worth building, and give your team the skills to use it.','Strategy, advisory & training']];
export default function Home(){
const [open,setOpen]=useState(false);const [particles,setParticles]=useState<Particle[]>([]);const reduced=useRef(false);const last=useRef(0);const count=useRef(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const hero=useRef<HTMLElement>(null);
function reset(){setParticles([]);if(hero.current)hero.current.dataset.active='false';}
useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');reduced.current=mq.matches;const update=()=>{reduced.current=mq.matches;if(mq.matches){setParticles([]);if(hero.current)hero.current.dataset.active='false';}};mq.addEventListener('change',update);return()=>{mq.removeEventListener('change',update);if(timer.current)clearTimeout(timer.current);};},[]);
function move(e:PointerEvent<HTMLElement>){if(reduced.current||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;e.currentTarget.style.setProperty('--px',`${x}px`);e.currentTarget.style.setProperty('--py',`${y}px`);e.currentTarget.dataset.active='true';if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(reset,1300);if(performance.now()-last.current<65)return;last.current=performance.now();const glyph=['0 1','> _','{ }','01','· ·'][count.current%5];setParticles(p=>[...p.slice(-15),{id:count.current++,x,y,glyph}]);}
return <main id="top"><header className="header"><a href="#top" aria-label="RexTexh home"><Image src="/brand/rextexh-logo.png" alt="RexTexh" width={1441} height={323} priority sizes="166px" className="logo"/></a><nav id="navigation" className={open?'open':''}>{links.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}<a className="mobile-contact" href="#contact" onClick={()=>setOpen(false)}>Let’s talk ↗</a></nav><a className="header-contact" href="#contact">Let’s talk <span>↗</span></a><button className="menu" aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?'Close':'Menu'}</button></header>
<section ref={hero} className="hero" onPointerMove={move} onPointerLeave={reset} aria-labelledby="hero-title"><div className="atmosphere" aria-hidden="true"/><div className="particles" aria-hidden="true">{particles.map(p=><span key={p.id} style={{left:p.x,top:p.y} as CSSProperties}>{p.glyph}</span>)}</div><div className="hero-content"><p className="eyebrow">Practical AI. Real business.</p><h1 id="hero-title">Better work.<br/><em>Built with AI.</em></h1><p className="hero-description">Turn everyday bottlenecks into useful software,<br className="desktop-break"/> connected workflows, and time back for your team.</p><div className="actions"><a className="button primary" href="#contact">Find your starting point <span>↗</span></a><a className="text-link" href="#example">See what that looks like <span>↓</span></a></div><p className="hero-note">Strategy · Software · Automation · Training</p></div><div className="horizon" aria-hidden="true"><div/><div/><div/></div><div className="hero-bottom"><span>Built around your business. Not the hype.</span><span>Explore what’s possible ↓</span></div></section>
<section id="example" className="example section"><div className="section-heading"><p className="eyebrow">From busywork to better work</p><h2>Same team.<br/>A simpler way to work.</h2><p>A weekly report shouldn’t take a week of chasing.<br/>Here’s one way a connected workflow could help.</p></div><div className="demo" onPointerMove={(e)=>{if(reduced.current||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--dx',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--dy',`${e.clientY-r.top}px`);e.currentTarget.dataset.lit='true';}} onPointerLeave={(e)=>{e.currentTarget.dataset.lit='false';}} aria-label="Illustrative reporting workflow"><div className="demo-top"><span><i/> Weekly operations report</span><span>Illustrative example · not client results</span></div><div className="demo-body"><div className="sources"><small>YOUR EVERYDAY TOOLS</small>{['Team updates','Sales spreadsheet','Customer requests'].map((s,i)=><div key={s}><b>{['↗','▦','≡'][i]}</b>{s}<span>→</span></div>)}</div><div className="connection" aria-hidden="true"><span>Collect</span><div/><span>Organize</span><div/><span>Summarize</span></div><div className="output"><div className="output-label">READY FOR YOUR REVIEW <span>✓</span></div><h3>Your week, in focus.</h3><p>One clear summary.<br/>Updates, priorities and follow-ups.</p><div className="report-line"/><div className="report-line short"/><div className="review"><span>Human review</span><span>Before sharing ↗</span></div></div></div><div className="demo-bottom">Less copying between tools. More time to act on what matters.</div></div></section>
<section id="services" className="services"><div className="section services-inner"><div className="section-heading"><p className="eyebrow">What we build together</p><h2>Useful systems.<br/>Not another tool to manage.</h2></div>{services.map(([number,title,copy,label])=><article className="service" key={number}><span className="service-number">/{number}</span><div><small>{label}</small><h3>{title}</h3></div><p>{copy}</p></article>)}</div></section>
<section id="approach" className="section approach"><div><p className="eyebrow">The RexTexh approach</p><h2>Understand first.<br/>Build what matters.</h2><p>Not every problem needs a chatbot.<br/>We help you choose the simplest useful solution.</p></div><ol>{[['Understand','Start with your workflow, your people and the bottleneck.'],['Build','Turn a clear plan into a practical, working system.'],['Make it stick','Help your team use it, learn from it and improve it.']].map(([t,p])=><li key={t}><h3>{t}</h3><p>{p}</p></li>)}</ol></section>
<section id="learn" className="learn section"><span className="learn-symbol" aria-hidden="true">&lt; / &gt;</span><div><p className="eyebrow">Prompt-to-Code with Rex</p><h2>Don’t just use AI.<br/>Understand what you can do with it.</h2><p>Practical training and mentoring for teams, founders and builders.<br/>Learn by working on something useful.</p><a className="text-link" href="#contact">Talk about training <span>↗</span></a></div></section>
<section id="contact" className="contact"><p className="eyebrow">Start with a conversation</p><h2>What could work<br/><em>better in your business?</em></h2><p>You don’t need a technical brief.<br/>Just a problem worth solving.</p><div className="booking-pending" role="note">Call booking will be available here soon.</div><p className="contact-note">Booking link pending confirmation. No details are collected on this page.</p></section>
<footer className="footer"><a href="#top" aria-label="RexTexh home"><Image src="/brand/rextexh-logo.png" alt="RexTexh" width={1441} height={323} sizes="166px" className="logo"/></a><p>Useful AI. Clear workflows. Practical systems.</p><a href="#top">Back to top ↑</a></footer></main>;
}
